<?php

$title = "Edit mail page";
$this->headTitle($title);

?>
<h1><?= $title ?></h1>


<table class="table">
    <tr>
        <th>Date</th>
        <th>From</th>
        <th>Subject</th>
        <th>Content</th>
    </tr>
    <tr>
        <td> <?= $mail['date'] ?> </td>
        <td> <?= $mail['from'] ?> </td>
        <td> <?= $mail['subject'] ?> </td>
        <td> <?= $mail['content'] ?> </td>

    </tr>
</table>

