<?php

$title = "Mail main page";
$this->headTitle($title);

?>
<h1><?= $title ?></h1>

<table class="table">
    <tr>
        <th>Date</th>
        <th>From</th>
        <th>Subject</th>
        <th>Content</th>
    </tr>

    <?php foreach ($mails as $mail) { ?>
        <tr>
            <td> <?= $mail['date'] ?> </td>
            <td> <?= $mail['from'] ?> </td>
            <td> <?= $mail['subject'] ?> </td>
            <td> <?= $mail['content'] ?> </td>

        </tr>
        <?php
    }
    ?>
</table>


